---
title: "R Notebook"
output: html_notebook
---

# Loading all relevant packages
```{r}
# load in tidyverse
library(tidyverse)
library(ggplot2)
#library(xtable)
library(ggthemes)
library(RColorBrewer)
library(extrafont)
```

#Loading the data
```{r}
# Assign csv file to a variable
Spotify<- read_csv("top10s.csv")

# Rename variable top genre to genre
names(Spotify)[names(Spotify) == 'top genre'] <- 'genre'

# Select correct columns
spotify_filtered <- Spotify %>%
  select('genre', pop, year)
```


```{r}
# read in new file
GenresCombined <- read_csv('GenresCombined.csv')
# Combine two files
spotify_filtered <- left_join(spotify_filtered, GenresCombined, by = 'genre')


```


```{r}
# Make the values for year numeric, and rename the columns
spotify_filtered <- spotify_filtered %>%
  mutate (
    year = as.Date(paste0(year,"-1-1"),"%Y-%m-%d")
  )

names(spotify_filtered)[names(spotify_filtered) == 'genre'] <- 'many_genres'
names(spotify_filtered)[names(spotify_filtered) == 'classified_genre'] <- 'Genre'

```

# Creating the plot(s)
```{r}
spotify_filtered_new <- spotify_filtered %>%
  group_by(Genre) %>%
  summarize(total = mean(pop, na.rm = TRUE)) %>%
  na.omit()

#creating a bar graph
ggplot(data = spotify_filtered_new) +
  geom_col(mapping = aes(
    x = reorder(Genre, -total), y = total)) + 
    xlab("Genres") + ylab("Average popularity score") +
    ggtitle("Popularity scores per music genre (2010-2019)") +
    #theme_hc() +
    #theme(text=element_text(family = "CMU Serif")) +
    ggsave("Total_popularity_per_genre_spotify.pdf")

#creating a violin graph with genre and pop score
ggplot(data = remove_missing(spotify_filtered)) +
  geom_violin(mapping = aes(
    x = reorder(Genre, -pop), y = pop, fill = Genre, na.rm = TRUE)) +
    theme_hc() +
    theme(legend.position = "none", 
          axis.text.x = element_text(angle=30), 
          text = element_text(family = "CMU Serif"))  +
    xlab("Genres") + ylab("Popularity score") +
    ggtitle("Popularity score per music genre (2010-2019)") +
  geom_point(mapping = aes(x=Genre, y = pop)) +
     ggsave("Violin_graph_spotify.pdf") 
```