---
title: "Visualisation in R"
output: html_notebook
---


```{r}
#install.packages("ggthemes")
#install.packages("xtable")
```

```{r}
#install.packages("extrafont")
```



```{r}
library(tidyverse)
library(xtable)
library(ggthemes)
library(RColorBrewer)
#library(extrafont)
#font_import()
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
```

```{r}
musicians <- read_csv('genres_data.csv')
genres <- read_csv('genres-mapping.csv')
#conflict <- read_csv('relevant_data_years_type.csv')
```

```{r}
```

```{r}
musicians <- left_join(musicians, genres, by='genre')
```


```{r}
musicians <- musicians %>%
  mutate(
    many_genres = genre,
    Genre = classified_genre,
    Year = as.numeric(year)
  ) %>%
  filter(year > 1900)

Number_of_genres <- musicians %>%
  group_by(Genre, Year) %>%
  summarize(n_genres = n()) %>%
  arrange(desc(n_genres))

musicians_10 <- musicians %>%
  filter(classified_genre == "Pop music" |
         classified_genre == "Hip hop music" |
         classified_genre == "Rock music" | 
         classified_genre == "Alternative rock" | 
         classified_genre == "Pop rock" |
         classified_genre == "Country music" |
         classified_genre == "Folk music" |
         classified_genre == "Heavy metal music" |
         classified_genre == "Rhythm and blues" |
         classified_genre == "Soul music")
```

```{r}
musicians <- left_join(musicians, genres, by='genre')
```


```{r}
Number_of_genre_news <- musicians_10 %>%
  group_by(classified_genre) %>%
  summarize(n_genres = n()) %>%
  arrange(desc(n_genres))
```



```{r}
ggplot(musicians_10) + 
  geom_count(mapping = aes(x = Year, y = Genre, color = Genre), alpha = 0.7) +
  guides(color = FALSE) + 
  scale_size_area() +
  ggtitle("New artists by genre over time") +
  theme_economist() +
  theme(text=element_text(family="serif(roman)",face="bold")) +
   ggsave("dotplot.pdf")
```


```{r}
Number_of_genre_new <- musicians_10 %>%
  group_by(Genre, Year) %>%
  summarize(n_genres = n()) %>%
  arrange(desc(n_genres))

ggplot(Number_of_genre_new) +
  geom_line(mapping = aes(x = Year, y = n_genres, color = Genre)) +
  xlab("Year") + ylab("Number of new artists") +
  ggtitle("New artists by genre") +
  theme_economist() +
  ggsave("Linegraph_artists.pdf") 
```

```{r}
Number_of_genres %>%
  filter(
    Genre == "Dance music" |
    Genre == "Pop  music" | 
    Genre == "Hip hop music"
  ) %>% 
  ggplot() +
  geom_line(mapping = aes(x = Year, y = n_genres, color = Genre))
```

